---
title: "Metode"
format: html
---

```{r}
##Loading necessary items

#| echo: false
#| warning: false
library(repeatData)
library(readxl)
library(tidyverse)
library(gt)
library(lme4)
library(irr)


data(final.data)
data("cycling.data")
```



##Descriptive statistics for the paeticipants

```{r}
descript <- final.data %>% 
select(id, timepoint, test, period, sex, weight, height, age, vo2.kg, rel.vo2, vo2, watt) %>% 
  filter(period == 1, test == "max", timepoint == "pre", 
         !id %in% c(6,11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57)) %>% 
  mutate(bmi = weight/(height/100)^2) %>% 
  group_by() %>% 
 summarise(N = n(), 
            Age = paste(round(mean(age, na.rm = TRUE),2), 
                        round(sd(age, na.rm = TRUE),2), 
                        sep = " ± "),
            Weight = paste(round(mean(weight, na.rm = TRUE),2), 
                        round(sd(weight, na.rm = TRUE),2), 
                        sep = " ± "),
            BMI = paste(round(mean(bmi, na.rm = TRUE),2), 
                        round(sd(bmi, na.rm = TRUE),2), 
                        sep = " ± "),
           rel.VO2max = paste(round(mean(vo2.kg, na.rm = TRUE),2), 
                        round(sd(vo2.kg, na.rm = TRUE),2), 
                        sep = " ± "),
           VO2max = paste(round(mean(vo2, na.rm = TRUE),2), 
                        round(sd(vo2, na.rm = TRUE),2), 
                        sep = " ± "),
           Wmax = paste(round(mean(watt, na.rm = TRUE),2), 
                        round(sd(watt, na.rm = TRUE),2), 
                        sep = " ± ")) %>% 
 mutate(N = as.character(N)) %>% 
  pivot_longer(names_to = "variables",
               values_to = "values",
               cols = N:Wmax) %>% 
  mutate(
    variables = case_when(
      variables == "rel.VO2max" ~ "VO2max (ml/kg/min)",
      variables == "Weight" ~ "Body weight (kg)",
      variables == "VO2max" ~ "VO2max (ml/min)",
       variables == "Wmax" ~ "Wmax (watt)",
      variables == "Age" ~ "Age (years)",
      TRUE ~ variables))
 


descript.2 <- final.data %>% 
 select(id, timepoint, test, period, watt) %>% 
  filter(period == 1, test == "per", timepoint == "pre", 
         !id %in% c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57)) %>% 
  group_by() %>% 
  summarise(
    variables = "15min avg (watt)",
    values = paste(round(mean(watt, na.rm = TRUE), 2), 
                   round(sd(watt, na.rm = TRUE), 2), 
                   sep = " ± "))


descript_combined <- rbind(descript, descript.2)
print(descript_combined)

gt(descript_combined) %>% 
cols_label(variables = "Variables",
           values = "Mean ± SD") %>% 
  tab_header(title = "Characteristics of the participants")
descript_combined
```

