---
title: "session-data"
format: html
---


```{r}
##Loading necessary items

#| echo: false
#| warning: false
library(repeatData)
library(readxl)
library(tidyverse)
library(gt)
library(lme4)
library(irr)
library(cowplot)
library(psych)
library(ggplot2)
library(webshot2)

data(final.data)
data("cycling.data")
data("hb.data")


```


## RPE

```{r}
session.rpe66 <- session.data %>% 
  filter(!id %in% c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57),
         type == "6x6") %>%
  pivot_wider(names_from = period, values_from = ftp:rpe) %>% 
  group_by(id) %>%
  summarize(mean_rpe_1 = mean(rpe_1, na.rm=T),
            mean_rpe_2 = mean(rpe_2, na.rm=T)) %>%
  pivot_longer(cols = starts_with("mean_rpe"),
               names_to = "test",
               values_to = "rpe") %>%
  mutate(period = if_else(test == "mean_rpe_1", "1", "2")) %>%
  select(id, period, rpe) %>% 
print()

  model.sess.rpe66 <- lmer(rpe ~ period + (1 | id), data = session.rpe66)
  summary(model.sess.rpe66) 
    
  
  irr.icc.rpe66 <- session.rpe66 %>% 
  select(id, period, rpe) %>% 
  pivot_wider(names_from = period, values_from = rpe, names_prefix = "per_") %>% 
  select(per_1, per_2) %>% 
  print()
  
  irr.icc.rpe66.result <- icc(irr.icc.rpe66, model = "twoway", type = "agreement", unit = "single")

# Extract ICC and confidence intervals
icc_value.rpe66 <- irr.icc.rpe66.result$value
lower_ci.rpe66 <- irr.icc.rpe66.result$lbound
upper_ci.rpe66 <- irr.icc.rpe66.result$ubound
  

# Define the function to calculate CV
calculate_cv <- function(data, workout_type, variable, exclude_ids = c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57)) {
  variable_1 <- paste0(variable, "_1")
  variable_2 <- paste0(variable, "_2")
  
  data %>%
    filter(!id %in% exclude_ids, type == workout_type) %>%
    pivot_wider(names_from = period, values_from = c(rpe, watt, hr)) %>%
    group_by(id) %>%
    summarize(mean_1 = mean(!!sym(variable_1), na.rm = TRUE),
              mean_2 = mean(!!sym(variable_2), na.rm = TRUE)) %>%
    pivot_longer(cols = starts_with("mean"),
                 names_to = "test",
                 values_to = variable) %>%
    mutate(period = if_else(test == "mean_1", "1", "2")) %>%
    select(id, period, all_of(variable)) %>%
    pivot_wider(names_from = period, values_from = all_of(variable), names_prefix = "p_") %>%
    mutate(diff = p_2 - p_1) %>%
    summarise(mean_diff = mean(diff, na.rm = TRUE),
              mean = mean(c(p_1, p_2), na.rm = TRUE),
              sd_diff = sd(diff, na.rm = TRUE),
              te = sd_diff / sqrt(2),
              cv = (te / mean) * 100)
}



cv.rpe66 <- calculate_cv(session.data, "6x6", "rpe")

df.s66.rpe.plot <- session.rpe66 %>%
  filter(period %in% c(1, 2)) %>%
  spread(key = period, value = rpe) %>%
  rename(Pre1 = '1', Pre2 = '2')


 s66.rpe.plot <- ggplot(df.s66.rpe.plot, aes(x = Pre1, y = Pre2)) +
 geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
   scale_x_continuous(limits = c(11, 16), breaks = seq(11, 16, by = 1), expand = c(0, 0),
                       labels = function(x) ifelse(x == 11, 0, x)) +
  scale_y_continuous(limits = c(11, 16), breaks = seq(11, 16, by = 1), expand = c(0, 0),
                      labels = function(x) ifelse(x == 11, 0, x)) +
   coord_fixed(ratio = 1) +
  labs(x = "Period 1", y = "Period 2") +
     annotate("text", x = 11.2, y = 15.8, 
              label = paste("ICC =", round(icc_value.rpe66, 2),
                   "[", round(lower_ci.rpe66, 2), ",", round(upper_ci.rpe66, 2), "]"),
              hjust = 0, vjust = 1) +
   annotate("text", x = 11.2, y = 15.3, 
              label = paste("CV =", round(cv.rpe66$cv, 2)),
                             hjust = 0, vjust = 1) +
     theme_minimal() +
  theme(
    panel.grid = element_blank(),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    axis.text = element_text(size = 12))
 s66.rpe.plot

```

```{r}
session.rpe48 <- session.data %>% 
  filter(!id %in% c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57),
         type == "4x8") %>%
  pivot_wider(names_from = period, values_from = ftp:rpe) %>% 
  group_by(id) %>%
  summarize(mean_rpe_1 = mean(rpe_1, na.rm = TRUE),
            mean_rpe_2 = mean(rpe_2, na.rm = TRUE)) %>%
  pivot_longer(cols = starts_with("mean_rpe"),
               names_to = "test",
               values_to = "rpe") %>%
  mutate(period = if_else(test == "mean_rpe_1", "1", "2")) %>%
  select(id, period, rpe) %>% 
  print()

model.sess.rpe48 <- lmer(rpe ~ period + (1 | id), data = session.rpe48)
summary(model.sess.rpe48)

  irr.icc.rpe48 <- session.rpe48 %>% 
  select(id, period, rpe) %>% 
  pivot_wider(names_from = period, values_from = rpe, names_prefix = "per_") %>% 
  select(per_1, per_2) %>% 
  print()
  
  irr.icc.rpe48.result <- icc(irr.icc.rpe48, model = "twoway", type = "agreement", unit = "single")

# Extract ICC and confidence intervals
icc_value.rpe48 <- irr.icc.rpe48.result$value
lower_ci.rpe48 <- irr.icc.rpe48.result$lbound
upper_ci.rpe48 <- irr.icc.rpe48.result$ubound
  



cv.rpe48 <- calculate_cv(session.data, "4x8", "rpe")



df.s48.rpe.plot <- session.rpe48 %>%
  filter(period %in% c(1, 2)) %>%
  spread(key = period, value = rpe) %>%
  rename(Pre1 = '1', Pre2 = '2')

s48.rpe.plot <- ggplot(df.s48.rpe.plot, aes(x = Pre1, y = Pre2)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
   scale_x_continuous(limits = c(14, 20), breaks = seq(14, 20, by = 1), expand = c(0, 0),
                       labels = function(x) ifelse(x == 14, 0, x)) +
  scale_y_continuous(limits = c(14, 20), breaks = seq(14, 20, by = 1), expand = c(0, 0),
                      labels = function(x) ifelse(x == 14, 0, x)) +
  coord_fixed(ratio = 1) +
  labs(x = "Period 1", y = "Period 2") +
  annotate("text", x = 14.2, y = 19.8, 
           label = paste("ICC =", round(icc_value.rpe48, 2),
                         "[", round(lower_ci.rpe48, 2), ",", round(upper_ci.rpe48, 2), "]"),
           hjust = 0, vjust = 1) +
  annotate("text", x = 14.2, y = 19.3, 
              label = paste("CV =", round(cv.rpe48$cv, 2)),
                             hjust = 0, vjust = 1) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    axis.text = element_text(size = 12))
s48.rpe.plot

```

```{r}
session.rpe45 <- session.data %>% 
  filter(!id %in% c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57),
         type == "4x5") %>%
  pivot_wider(names_from = period, values_from = ftp:rpe) %>% 
  group_by(id) %>%
  summarize(mean_rpe_1 = mean(rpe_1, na.rm = TRUE),
            mean_rpe_2 = mean(rpe_2, na.rm = TRUE)) %>%
  pivot_longer(cols = starts_with("mean_rpe"),
               names_to = "test",
               values_to = "rpe") %>%
  mutate(period = if_else(test == "mean_rpe_1", "1", "2")) %>%
  select(id, period, rpe) %>% 
  print()

model.sess.rpe45 <- lmer(rpe ~ period + (1 | id), data = session.rpe45)
summary(model.sess.rpe45)

confint(model.sess.rpe45)

irr.icc.rpe45 <- session.rpe45 %>% 
  select(id, period, rpe) %>% 
  pivot_wider(names_from = period, values_from = rpe, names_prefix = "per_") %>% 
  select(per_1, per_2) %>% 
  print()

irr.icc.rpe45.result <- icc(irr.icc.rpe45, model = "twoway", type = "agreement", unit = "single")

# Extract ICC and confidence intervals
icc_value.rpe45 <- irr.icc.rpe45.result$value
lower_ci.rpe45 <- irr.icc.rpe45.result$lbound
upper_ci.rpe45 <- irr.icc.rpe45.result$ubound


cv.rpe45 <- calculate_cv(session.data, "4x5", "rpe")



df.s45.rpe.plot <- session.rpe45 %>%
  filter(period %in% c(1, 2)) %>%
  spread(key = period, value = rpe) %>%
  rename(Pre1 = '1', Pre2 = '2')

s45.rpe.plot <- ggplot(df.s45.rpe.plot, aes(x = Pre1, y = Pre2)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_continuous(limits = c(15, 20), expand = c(0, 0)) +
  scale_y_continuous(limits = c(15, 20), expand = c(0, 0)) +
  scale_x_continuous(limits = c(15, 20), breaks = seq(15, 20, by = 1), expand = c(0, 0),
                       labels = function(x) ifelse(x == 15, 0, x)) +
  scale_y_continuous(limits = c(15, 20), breaks = seq(15, 20, by = 1), expand = c(0, 0),
                      labels = function(x) ifelse(x == 15, 0, x)) +
  coord_fixed(ratio = 1) +
  labs(x = "Period 1", y = "Period 2") +
  annotate("text",x = 15.2, y = 19.8, 
           label = paste("ICC =", round(icc_value.rpe45, 2),
                         "[", round(lower_ci.rpe45, 2), ",", round(upper_ci.rpe45, 2), "]"),
           hjust = 0, vjust = 1) +
  annotate("text", x = 15.2, y = 19.3, 
              label = paste("CV =", round(cv.rpe45$cv, 2)),
                             hjust = 0, vjust = 1) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    axis.text = element_text(size = 12))
s45.rpe.plot

```

```{r}
session.w66 <- session.data %>% 
  filter(!id %in% c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57),
         type == "6x6") %>%
  pivot_wider(names_from = period, values_from = ftp:rpe) %>% 
  group_by(id) %>% 
  summarize(mean_watt_1 = mean(watt_1, na.rm=T),
            mean_watt_2 = mean(watt_2, na.rm=T)) %>%
  pivot_longer(cols = starts_with("mean_watt"),
               names_to = "test",
               values_to = "watt") %>%
  mutate(period = if_else(test == "mean_watt_1", "1", "2")) %>%
  select(id, period, watt) %>% 
  print()

##different models 

  model.w66 <- lmer(watt ~ period + (1 | id), data = session.w66)
  summary(model.w66) 
    
  confint(model.w66)
  
 irr.icc.w66 <- session.w66 %>% 
  select(id, period, watt) %>% 
  pivot_wider(names_from = period, values_from = watt, names_prefix = "per_") %>% 
  select(per_1, per_2) %>% 
  print()

irr.icc.w66.result <- icc(irr.icc.w66, model = "twoway", type = "agreement", unit = "single")

# Extract ICC and confidence intervals
icc_value.w66 <- irr.icc.w66.result$value
lower_ci.w66 <- irr.icc.w66.result$lbound
upper_ci.w66 <- irr.icc.w66.result$ubound


cv.w66 <- calculate_cv(session.data, "6x6", "watt")


df.s66.w.plot <- session.w66 %>%
  filter(period %in% c(1, 2)) %>%
  spread(key = period, value = watt) %>%
  rename(Pre1 = '1', Pre2 = '2') %>% 
  print()

s66.w.plot <- ggplot(df.s66.w.plot, aes(x = Pre1, y = Pre2)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_continuous(limits = c(25, 200), breaks = seq(25, 200, by = 50), expand = c(0, 0),
                       labels = function(x) ifelse(x == 25, 0, x)) +
  scale_y_continuous(limits = c(25, 200), breaks = seq(25, 200, by = 50), expand = c(0, 0),
                      labels = function(x) ifelse(x == 25, 0, x)) +
  coord_fixed(ratio = 1) +
  labs(x = "Period 1", y = "Period 2") +
  annotate("text",x = 35, y = 195, 
           label = paste("ICC =", round(icc_value.w66, 2),
                         "[", round(lower_ci.w66, 2), ",", round(upper_ci.w66, 2), "]"),
           hjust = 0, vjust = 1) +
  annotate("text", x = 35, y = 175, 
              label = paste("CV =", round(cv.w66$cv, 2)),
                             hjust = 0, vjust = 1) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    axis.text = element_text(size = 12))
s66.w.plot




```

```{r}
session.hr45 <- session.data %>% 
  filter(!id %in% c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57),
         type == "4x5") %>%
  pivot_wider(names_from = period, values_from = ftp:rpe) %>% 
  group_by(id) %>% 
  summarize(mean_hr_1 = mean(hr_1, na.rm = TRUE),
            mean_hr_2 = mean(hr_2, na.rm = TRUE)) %>%
  pivot_longer(cols = starts_with("mean_hr"),
               names_to = "test",
               values_to = "hr") %>%
  mutate(period = if_else(test == "mean_hr_1", "1", "2")) %>%
  select(id, period, hr) %>% 
  print()

## Different models 

model.hr45 <- lmer(hr ~ period + (1 | id), data = session.hr45)
summary(model.hr45)

confint(model.hr45)

irr.icc.hr45 <- session.hr45 %>% 
  select(id, period, hr) %>% 
  pivot_wider(names_from = period, values_from = hr, names_prefix = "per_") %>% 
  select(per_1, per_2) %>% 
  print()

irr.icc.hr45.result <- icc(irr.icc.hr45, model = "twoway", type = "agreement", unit = "single")

# Extract ICC and confidence intervals
icc_value.hr45 <- irr.icc.hr45.result$value
lower_ci.hr45 <- irr.icc.hr45.result$lbound
upper_ci.hr45 <- irr.icc.hr45.result$ubound



cv.hr45 <- calculate_cv(session.data, "4x5", "hr")


df.s45.hr.plot <- session.hr45 %>%
  filter(period %in% c(1, 2)) %>%
  spread(key = period, value = hr) %>%
  rename(Pre1 = '1', Pre2 = '2') %>% 
  print()

s45.hr.plot <- ggplot(df.s45.hr.plot, aes(x = Pre1, y = Pre2)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
   scale_x_continuous(limits = c(105, 170), breaks = seq(105, 170, by = 15), expand = c(0, 0),
                       labels = function(x) ifelse(x == 105, 0, x)) +
  scale_y_continuous(limits = c(105, 170), breaks = seq(105, 170, by = 15), expand = c(0, 0),
                      labels = function(x) ifelse(x == 105, 0, x)) +
  coord_fixed(ratio = 1) +
  labs(x = "Period 1", y = "Period 2") +
  annotate("text", x = 107, y = 168, 
           label = paste("ICC =", round(icc_value.hr45, 2),
                         "[", round(lower_ci.hr45, 2), ",", round(upper_ci.hr45, 2), "]"),
           hjust = 0, vjust = 1) +
   annotate("text", x = 107, y = 161, 
              label = paste("CV =", round(cv.hr45$cv, 2)),
                             hjust = 0, vjust = 1) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    axis.text = element_text(size = 12))
s45.hr.plot
```

```{r}
session.hr48 <- session.data %>% 
  filter(!id %in% c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57),
         type == "4x8") %>%
  pivot_wider(names_from = period, values_from = ftp:rpe) %>% 
  group_by(id) %>% 
  summarize(mean_hr_1 = mean(hr_1, na.rm = TRUE),
            mean_hr_2 = mean(hr_2, na.rm = TRUE)) %>%
  pivot_longer(cols = starts_with("mean_hr"),
               names_to = "test",
               values_to = "hr") %>%
  mutate(period = if_else(test == "mean_hr_1", "1", "2")) %>%
  select(id, period, hr) %>% 
  print()

## Different models 

model.hr48 <- lmer(hr ~ period + (1 | id), data = session.hr48)
summary(model.hr48)

confint(model.hr48)

irr.icc.hr48 <- session.hr48 %>% 
  select(id, period, hr) %>% 
  pivot_wider(names_from = period, values_from = hr, names_prefix = "per_") %>% 
  select(per_1, per_2) %>% 
  print()

irr.icc.hr48.result <- icc(irr.icc.hr48, model = "twoway", type = "agreement", unit = "single")

# Extract ICC and confidence intervals
icc_value.hr48 <- irr.icc.hr48.result$value
lower_ci.hr48 <- irr.icc.hr48.result$lbound
upper_ci.hr48 <- irr.icc.hr48.result$ubound



cv.hr48 <- calculate_cv(session.data, "4x8", "hr")

df.s48.hr.plot <- session.hr48 %>%
  filter(period %in% c(1, 2)) %>%
  spread(key = period, value = hr) %>%
  rename(Pre1 = '1', Pre2 = '2') %>% 
  print()

s48.hr.plot <- ggplot(df.s48.hr.plot, aes(x = Pre1, y = Pre2)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
   scale_x_continuous(limits = c(110, 175), breaks = seq(110, 175, by = 15), expand = c(0, 0),
                       labels = function(x) ifelse(x == 110, 0, x)) +
  scale_y_continuous(limits = c(110, 175), breaks = seq(110, 175, by = 15), expand = c(0, 0),
                      labels = function(x) ifelse(x == 110, 0, x)) +
  coord_fixed(ratio = 1) +
  labs(x = "Period 1", y = "Period 2") +
  annotate("text", x = 111, y = 173, 
           label = paste("ICC =", round(icc_value.hr48, 2),
                         "[", round(lower_ci.hr48, 2), ",", round(upper_ci.hr48, 2), "]"),
           hjust = 0, vjust = 1) +
   annotate("text", x = 111, y = 166, 
              label = paste("CV =", round(cv.hr48$cv, 2)),
                             hjust = 0, vjust = 1) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    axis.text = element_text(size = 12))
s48.hr.plot

```

```{r}
session.hr66 <- session.data %>% 
  filter(!id %in% c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57),
         type == "6x6") %>%
  pivot_wider(names_from = period, values_from = ftp:rpe) %>% 
  group_by(id) %>% 
  summarize(mean_hr_1 = mean(hr_1, na.rm = TRUE),
            mean_hr_2 = mean(hr_2, na.rm = TRUE)) %>%
  pivot_longer(cols = starts_with("mean_hr"),
               names_to = "test",
               values_to = "hr") %>%
  mutate(period = if_else(test == "mean_hr_1", "1", "2")) %>%
  select(id, period, hr) %>% 
  print()

## Different models 

model.hr66 <- lmer(hr ~ period + (1 | id), data = session.hr66)
summary(model.hr66)

confint(model.hr66)

irr.icc.hr66 <- session.hr66 %>% 
  select(id, period, hr) %>% 
  pivot_wider(names_from = period, values_from = hr, names_prefix = "per_") %>% 
  select(per_1, per_2) %>% 
  print()

irr.icc.hr66.result <- icc(irr.icc.hr66, model = "twoway", type = "agreement", unit = "single")

# Extract ICC and confidence intervals
icc_value.hr66 <- irr.icc.hr66.result$value
lower_ci.hr66 <- irr.icc.hr66.result$lbound
upper_ci.hr66 <- irr.icc.hr66.result$ubound


cv.hr66 <- calculate_cv(session.data, "6x6", "hr")



df.s66.hr.plot <- session.hr66 %>%
  filter(period %in% c(1, 2)) %>%
  spread(key = period, value = hr) %>%
  rename(Pre1 = '1', Pre2 = '2') %>% 
  print()

s66.hr.plot <- ggplot(df.s66.hr.plot, aes(x = Pre1, y = Pre2)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
     scale_x_continuous(limits = c(90, 165), breaks = seq(90, 165, by = 15), expand = c(0, 0),
                       labels = function(x) ifelse(x == 90, 0, x)) +
  scale_y_continuous(limits = c(90, 165), breaks = seq(90, 165, by = 15), expand = c(0, 0),
                      labels = function(x) ifelse(x == 90, 0, x)) +
  coord_fixed(ratio = 1) +
  labs(x = "Period 1", y = "Period 2") +
  annotate("text", x = 93, y = 163, 
           label = paste("ICC =", round(icc_value.hr66, 2),
                         "[", round(lower_ci.hr66, 2), ",", round(upper_ci.hr66, 2), "]"),
           hjust = 0, vjust = 1) +
   annotate("text", x = 93, y = 155, 
              label = paste("CV =", round(cv.hr66$cv, 2)),
                             hjust = 0, vjust = 1) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    axis.text = element_text(size = 12))
s66.hr.plot

```

```{r}
session.w48 <- session.data %>% 
  filter(!id %in% c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57),
         type == "4x8") %>%
  pivot_wider(names_from = period, values_from = ftp:rpe) %>% 
  group_by(id) %>% 
  summarize(mean_watt_1 = mean(watt_1, na.rm = TRUE),
            mean_watt_2 = mean(watt_2, na.rm = TRUE)) %>%
  pivot_longer(cols = starts_with("mean_watt"),
               names_to = "test",
               values_to = "watt") %>%
  mutate(period = if_else(test == "mean_watt_1", "1", "2")) %>%
  select(id, period, watt) %>% 
  print()

##different models 

model.w48 <- lmer(watt ~ period + (1 | id), data = session.w48)
summary(model.w48)

confint(model.w48)

irr.icc.w48 <- session.w48 %>% 
  select(id, period, watt) %>% 
  pivot_wider(names_from = period, values_from = watt, names_prefix = "per_") %>% 
  select(per_1, per_2) %>% 
  print()

irr.icc.w48.result <- icc(irr.icc.w48, model = "twoway", type = "agreement", unit = "single")

# Extract ICC and confidence intervals
icc_value.w48 <- irr.icc.w48.result$value
lower_ci.w48 <- irr.icc.w48.result$lbound
upper_ci.w48 <- irr.icc.w48.result$ubound



cv.w48 <- calculate_cv(session.data, "4x8", "watt")



df.s48.w.plot <- session.w48 %>%
  filter(period %in% c(1, 2)) %>%
  spread(key = period, value = watt) %>%
  rename(Pre1 = '1', Pre2 = '2') %>% 
  print()

s48.w.plot <- ggplot(df.s48.w.plot, aes(x = Pre1, y = Pre2)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
   scale_x_continuous(limits = c(25, 250), breaks = seq(25, 250, by = 50), expand = c(0, 0),
                       labels = function(x) ifelse(x == 25, 0, x)) +
  scale_y_continuous(limits = c(25, 250), breaks = seq(25, 250, by = 50), expand = c(0, 0),
                      labels = function(x) ifelse(x == 25, 0, x)) +
  coord_fixed(ratio = 1) +
  labs(x = "Period 1", y = "Period 2") +
  annotate("text", x = 35, y = 245, 
           label = paste("ICC =", round(icc_value.w48, 2),
                         "[", round(lower_ci.w48, 2), ",", round(upper_ci.w48, 2), "]"),
           hjust = 0, vjust = 1) +
   annotate("text", x = 35, y = 225, 
              label = paste("CV =", round(cv.w48$cv, 2)),
                             hjust = 0, vjust = 1) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    axis.text = element_text(size = 12))
s48.w.plot

```

```{r}
session.w45 <- session.data %>% 
  filter(!id %in% c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57),
         type == "4x5") %>%
  pivot_wider(names_from = period, values_from = ftp:rpe) %>% 
  group_by(id) %>% 
  summarize(mean_watt_1 = mean(watt_1, na.rm = TRUE),
            mean_watt_2 = mean(watt_2, na.rm = TRUE)) %>%
  pivot_longer(cols = starts_with("mean_watt"),
               names_to = "test",
               values_to = "watt") %>%
  mutate(period = if_else(test == "mean_watt_1", "1", "2")) %>%
  select(id, period, watt) %>% 
  print()


irr.icc.w45 <- session.w45 %>% 
  select(id, period, watt) %>% 
  pivot_wider(names_from = period, values_from = watt, names_prefix = "per_") %>% 
  select(per_1, per_2) %>% 
  print()

irr.icc.w45.result <- icc(irr.icc.w45, model = "twoway", type = "agreement", unit = "single")

# Extract ICC and confidence intervals
icc_value.w45 <- irr.icc.w45.result$value
lower_ci.w45 <- irr.icc.w45.result$lbound
upper_ci.w45 <- irr.icc.w45.result$ubound


## Different models 

model.w45 <- lmer(watt ~ period + (1 | id), data = session.w45)
summary(model.w45)

confint(model.w45)



cv.w45 <- calculate_cv(session.data, "4x5", "watt")


df.s45.w.plot <- session.w45 %>%
  filter(period %in% c(1, 2)) %>%
  spread(key = period, value = watt) %>%
  rename(Pre1 = '1', Pre2 = '2') %>% 
  print()

s45.w.plot <- ggplot(df.s45.w.plot, aes(x = Pre1, y = Pre2)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
   scale_x_continuous(limits = c(25, 250), breaks = seq(25, 250, by = 50), expand = c(0, 0),
                       labels = function(x) ifelse(x == 25, 0, x)) +
  scale_y_continuous(limits = c(25, 250), breaks = seq(25, 250, by = 50), expand = c(0, 0),
                      labels = function(x) ifelse(x == 25, 0, x)) +
  coord_fixed(ratio = 1) +
  labs(x = "Period 1", y = "Period 2") +
  annotate("text", x = 35, y = 245, 
           label = paste("ICC =", round(icc_value.w45, 2),
                         "[", round(lower_ci.w45, 2),",", round(upper_ci.w45, 2), "]"),
           hjust = 0, vjust = 1) +
   annotate("text", x = 35, y = 225, 
              label = paste("CV =", round(cv.w45$cv, 2)),
                             hjust = 0, vjust = 1) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
     axis.text = element_text(size = 12))
s45.w.plot

```

```{r}
comb.sess.plot <- plot_grid(s45.w.plot, s48.w.plot, s66.w.plot, s45.hr.plot, 
                            s48.hr.plot, s66.hr.plot, s45.rpe.plot, s48.rpe.plot, s66.rpe.plot,
                            ncol = 3,
                            labels = NULL)

# Add common labels for each column
labelled_plot.sess <- ggdraw(comb.sess.plot) +
  draw_label("4x5min", x = 0.17, y = 1.02, vjust = 1, size = 14, fontface = "bold") +
  draw_label("4x8min", x = 0.50, y = 1.02, vjust = 1, size = 14, fontface = "bold") +
  draw_label("6x6min", x = 0.83, y = 1.02, vjust = 1, size = 14, fontface = "bold") +
  draw_label("Watt", x = -0.01, y = 0.88, angle = 90, hjust = 1, size = 14, fontface = "bold") +
  draw_label("Heart Rate", x = -0.01, y = 0.54, angle = 90, hjust = 1, size = 14, fontface = "bold") +
  draw_label("RPE", x = -0.01, y = 0.25, angle = 90, hjust = 1, size = 14, fontface = "bold") +
     theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))

# Draw the final plot
# print(labelled_plot.sess)
                             
# ggsave("combined_plot.jpeg", plot = labelled_plot.sess, width = 8.27, height = 9, units = "in", dpi = 300)

```

## making a table Compareing session-data between period 1 and 2

```{r}
### Session data combined

session <- session.data %>% 
  filter(!id %in% c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57),
         type == c("4x5", "4x8", "6x6")) %>%
select(id, period, session.n, hr, watt, rpe) %>% 
  pivot_wider(names_from = period, values_from = hr:rpe) %>% 
  summarise(
  hr_1_mean = round(mean(hr_1, na.rm = TRUE)),
  watt_1_mean = round(mean(watt_1, na.rm = TRUE)),
  rpe_1_mean = round(mean(rpe_1, na.rm = TRUE)),
  hr_2_mean = round(mean(hr_2, na.rm = TRUE)),
  watt_2_mean = round(mean(watt_2, na.rm = TRUE)),
  rpe_2_mean = round(mean(rpe_2, na.rm = TRUE))) %>%
  pivot_longer(
    cols = starts_with("hr_1_"):starts_with("rpe_2_"),
    names_to = c(".value", "period"),
    names_sep = "_") %>%
pivot_longer(names_to = "variables", values_to = "values", cols = hr:rpe) %>% 
  pivot_wider(names_from = period, values_from = values, names_prefix = "period_") %>% 
  print()


### Session data one the 4x5 workouts



session45 <- session.data %>% 
  filter(!id %in% c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57),
         type == c("4x5")) %>%
select(id, period, session.n, hr, watt, rpe) %>% 
  pivot_wider(names_from = period, values_from = hr:rpe) %>% 
  summarise(
  hr_1_mean = round(mean(hr_1, na.rm = TRUE)),
  watt_1_mean = round(mean(watt_1, na.rm = TRUE)),
  rpe_1_mean = round(mean(rpe_1, na.rm = TRUE)),
  hr_2_mean = round(mean(hr_2, na.rm = TRUE)),
  watt_2_mean = round(mean(watt_2, na.rm = TRUE)),
  rpe_2_mean = round(mean(rpe_2, na.rm = TRUE))) %>%
  pivot_longer(
    cols = starts_with("hr_1_"):starts_with("rpe_2_"),
    names_to = c(".value", "period"),
    names_sep = "_") %>%
pivot_longer(names_to = "variables", values_to = "values", cols = hr:rpe) %>% 
  pivot_wider(names_from = period, values_from = values, names_prefix = "period_") %>% 
  print()


### Session data one the 4x8 workouts


session48 <- session.data %>% 
  filter(!id %in% c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57),
         type == c("4x8")) %>%
select(id, period, session.n, hr, watt, rpe) %>% 
  pivot_wider(names_from = period, values_from = hr:rpe) %>% 
  summarise(
  hr_1_mean = round(mean(hr_1, na.rm = TRUE)),
  watt_1_mean = round(mean(watt_1, na.rm = TRUE)),
  rpe_1_mean = round(mean(rpe_1, na.rm = TRUE)),
  hr_2_mean = round(mean(hr_2, na.rm = TRUE)),
  watt_2_mean = round(mean(watt_2, na.rm = TRUE)),
  rpe_2_mean = round(mean(rpe_2, na.rm = TRUE))) %>%
  pivot_longer(
    cols = starts_with("hr_1_"):starts_with("rpe_2_"),
    names_to = c(".value", "period"),
    names_sep = "_") %>%
pivot_longer(names_to = "variables", values_to = "values", cols = hr:rpe) %>% 
  pivot_wider(names_from = period, values_from = values, names_prefix = "period_") %>% 
  print()


### Session data one the 6x6 workouts



session66 <- session.data %>% 
  filter(!id %in% c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57),
         type == c("6x6")) %>%
select(id, period, session.n, hr, watt, rpe) %>% 
  pivot_wider(names_from = period, values_from = hr:rpe) %>% 
  summarise(
  hr_1_mean = round(mean(hr_1, na.rm = TRUE)),
  watt_1_mean = round(mean(watt_1, na.rm = TRUE)),
  rpe_1_mean = round(mean(rpe_1, na.rm = TRUE)),
  hr_2_mean = round(mean(hr_2, na.rm = TRUE)),
  watt_2_mean = round(mean(watt_2, na.rm = TRUE)),
  rpe_2_mean = round(mean(rpe_2, na.rm = TRUE))) %>%
  pivot_longer(
    cols = starts_with("hr_1_"):starts_with("rpe_2_"),
    names_to = c(".value", "period"),
    names_sep = "_") %>%
pivot_longer(names_to = "variables", values_to = "values", cols = hr:rpe) %>% 
  pivot_wider(names_from = period, values_from = values, names_prefix = "period_") %>% 
  print()



session_combined <- session.data %>% 
  filter(!id %in% c(6, 11, 20, 21, 25, 35, 37, 52, 53, 54, 56, 57)) %>% 
  filter(type %in% c("4x5", "4x8", "6x6")) %>%
  select(id, period, type, hr, watt, rpe) %>% 
  group_by(period, type) %>% 
  summarise(
    hr_mean = round(mean(hr, na.rm = TRUE), 2),
    hr_sd = round(sd(hr, na.rm = TRUE), 2),
    watt_mean = round(mean(watt, na.rm = TRUE), 2),
    watt_sd = round(sd(watt, na.rm = TRUE), 2),
    rpe_mean = round(mean(rpe, na.rm = TRUE), 2),
    rpe_sd = round(sd(rpe, na.rm = TRUE), 2)) %>% 
  mutate(
    hr = paste0(hr_mean, " ± ", hr_sd),
    watt = paste0(watt_mean, " ± ", watt_sd),
    rpe = paste0(rpe_mean, " ± ", rpe_sd)) %>% 
  select(period, type, hr, watt, rpe) %>% 
  print()
  
gt(session_combined)
```

